package com.borabora.csws.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "TempConvertImplService", targetNamespace = "http://csws.borabora.com/", wsdlLocation = "http://localhost:8080/ws/tc?wsdl")
public class TempConvertImplService
        extends Service {

    private final static URL TEMPCONVERTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.borabora.csws.client.TempConvertImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.borabora.csws.client.TempConvertImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ws/tc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ws/tc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEMPCONVERTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TempConvertImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConvertImplService() {
        super(TEMPCONVERTIMPLSERVICE_WSDL_LOCATION, new QName("http://csws.borabora.com/", "TempConvertImplService"));
    }

    /**
     * @return returns TempConvert
     */
    @WebEndpoint(name = "TempConvertImplPort")
    public TempConvert getTempConvertImplPort() {
        return super.getPort(new QName("http://csws.borabora.com/", "TempConvertImplPort"), TempConvert.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns TempConvert
     */
    @WebEndpoint(name = "TempConvertImplPort")
    public TempConvert getTempConvertImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://csws.borabora.com/", "TempConvertImplPort"), TempConvert.class, features);
    }

}
